### ISSUE TITLE
Future Improvement - User Feedback System

### ISSUE THREAD

**Issue by DesislavaNaydenova** [DesislavaNaydenova/pp5_cherry_leaves_mildew_detection#12]
**Description**  
Enable users to provide feedback on model predictions to improve performance over time.  

**Tasks**  
- [ ] Add a feedback form to the dashboard.
- [ ] Store feedback data in a database for analysis.
- [ ] Use the feedback data to fine-tune the model periodically.
- [ ] Visualize user feedback trends on the dashboard.
