### ISSUE TITLE
Deployment to Heroku

### ISSUE THREAD

**Issue by DesislavaNaydenova** [DesislavaNaydenova/pp5_cherry_leaves_mildew_detection#7]
**Description**  
Deploy the Streamlit dashboard to Heroku for easy accessibility.  

**Tasks**  
- [x] Set up Heroku project and link it to the GitHub repository.
- [x] Add `Procfile` and `requirements.txt` for deployment.
- [x] Use `.slugignore` to exclude large files (e.g., datasets).
- [x] Test the deployed app and fix any bugs.
